version: "2"
linters:
  default: standard
  disable:
    - errcheck
  generated: lax
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
issues:
  # See the dedicated "issues" documentation section.
  option: value
# Output configuration options.
output:
  # See the dedicated "output" documentation section.
  option: value
run:
  # See the dedicated "run" documentation section.
  option: value
severity:
  # See the dedicated "severity" documentation section.
  option: value
